### PR TITLE
[ch3636] Add payment link token lookup

### PR DESCRIPTION
**Pull request by coreymcmahon**
Adds the specification for `GET api/v4/payments/brands/{brand}/links/{token}`, which will be the endpoint for looking up a payment link session given a unique token:

```javascript
{
  "data": {
    "branch": {
      "id": 422,
      "locales": {
        "en": {
          "name": "McDonald's King Street",
          "short_name": "King Street"
        },
        "th": {
          "name": "โดนัลด์ ถนนพระราชา",
          "short_name": "ถนนพระราชา"
        }
      }
    },
    "brand": {
      "id": 52,
      "locales": {
        "en": {
          "name": "McDonald's"
        },
        "th": {
          "name": "โดนัลด์"
        }
      },
      "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg"
    },
    "customer": {
      "id": 10891,
      "name": "James Smith"
    },
    "line_items": [
      {
        "before_sale_price": 0,
        "extra_items": [
          {
            "id": 0,
            "locales": {
              "en": {
                "name": "Ketchup"
              },
              "th": {
                "name": "ซอสมะเขือเทศ"
              }
            },
            "price": 10
          }
        ],
        "id": 101,
        "locales": {
          "en": {
            "name": "Hamurbger"
          },
          "th": {
            "name": "แฮมเบอร์เกอร์"
          }
        },
        "price": 100,
        "quantity": 2
      }
    ],
    "order": {
      "id": 890121,
      "is_realtime": true,
      "reference": "S01-190100023",
      "scheduled_for": null,
      "type": "delivery"
    },
    "payment_gateway": {
      "configuration": "public_key=pkey_test_57wp8inyzr6ub4miwiq",
      "name": "Omise"
    },
    "totals": {
      "coupon_discount": 0,
      "delivery_fee": 50,
      "discount": 20,
      "discount_percentage": 0,
      "excluded_taxes": 0,
      "manual_price_adjustment": 0,
      "manual_price_adjustment_reason": null,
      "payment_fee": 0,
      "payment_fee_amount": 0,
      "payment_fee_fixed": null,
      "payment_fee_percentage": null,
      "payment_fee_type": "none",
      "rounding": 0,
      "service_fee": 0,
      "service_fee_percentage": 0,
      "subtotal": 165,
      "tax_mode": "inclusive",
      "taxable_amount": 0,
      "total": 195,
      "vat": 12.76,
      "vat_percentage": 7
    }
  }
}
```

### CODE REVIEW

**Comment by lezhnev74** [comment]
Comments:
- we need to know brandId in order to make this request. That means the actual link must include not only a token but also a brand id.
- the response body contains to TTL information. Does that mean that client need not know about that?

**Comment by coreymcmahon** [comment]
@lezhnev74 yes, we will need to include (at a minimum) the following information in the payment link:

* Unique payment token
* Brand ID
* Customer's preferred language (en|th)
* The API server that should be used for the payment link request (eg.: api.ginja.co.th, stagingapi.ginja.co.th)

And regarding TTL, we could include it if we want to show the expiration in the user interface, but it isn't currently included in the mockups.

**Comment by coreymcmahon** [comment]
Actually let's earmark these three things for discussion during standup:

1) Response payload above; does it include everything we need?
2) The actual payment link format; what information does it need to contain?
3) API url for retrieving payment links; should we include brand_id?

**Comment by coreymcmahon** [comment]
## Payment link structure

```
https://pay.foodkitapp.io/?token=23456789ghjkl&lang=en&brand=5&environment=staging
=>
https://tiny.url/9e2hhh2
```

* Client app will have a dictionary of `environment => server hostname`
* If `environment` is omitted, assume `production`

## Not found

```
GET api/v4/payments/brands/{brand}/links/{token}

HTTP 400 Client error
{
  "status": "not_found",
  "brand": {
    "id": 52,
    "customer_service_phone_number": "0202020202",
    "locales": {
      "en": {
        "name": "McDonald's"
      },
      "th": {
        "name": "Mcโดนัลด์"
      }
    },
    "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg"
  }
}
```

## Expired

```
GET api/v4/payments/brands/{brand}/links/{token}

HTTP 400 Client error
{
  "status": "expired",
  "brand": {
    "id": 52,
    "customer_service_phone_number": "0202020202",
    "locales": {
      "en": {
        "name": "McDonald's"
      },
      "th": {
        "name": "Mcโดนัลด์"
      }
    },
    "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg"
  }
}
```

## Other errors

E.g: 500's, request failed => just display a generic error message (unbranded).

**Comment by coreymcmahon** [comment]
One more edge case:

If the order has already been paid for, we need to tell the client to send the customer straight to the "success" page.

E.g:

```
GET api/v4/payments/brands/{brand}/links/{token}

200 OK
{
  "state": "paid",
  /* etc... */
}
```

**Comment by coreymcmahon** [comment]
```
# loading screen:
https://pay.foodkitapp.io/?token=23456789ghjkl&lang=en&brand=5&environment=staging
 - Put `token`, `lang`, `brand` and `environment` in localStorage

# error pages:
https://pay.foodkitapp.io/not-found
https://pay.foodkitapp.io/expired

# payment form (credit card):
https://pay.foodkitapp.io/payment
 - If user refreshes on this page, the user is redirected to the loading screen
   and we refresh the payment link state via the API (and redirect appropriately)

# payment success:
https://pay.foodkitapp.io/payment/success

# payment error:
https://pay.foodkitapp.io/payment/error
```

**Comment by coreymcmahon** [comment]
Remove `scheduled_for` and just send back the (client provided) date and time as such:

```
schedule_date = 2019-02-07
schedule_time = 10:00
```

**Comment by coreymcmahon** [comment]
image

In `orders` table we use payment_processing_fee instead of payment_fee.

**Comment by coreymcmahon** [comment]
## Possible error cases

```
{
  "brand": {
    "customer_service_phone_number": "8020202020",
    "id": 52,
    "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg",
    "name": "McDonald's"
  },
  "status": "expired"
}

{
  "brand": {
    "customer_service_phone_number": "8020202020",
    "id": 52,
    "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg",
    "name": "McDonald's"
  },
  "status": "not_found"
}

{
  "brand": {
    "customer_service_phone_number": "8020202020",
    "id": 52,
    "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg",
    "name": "McDonald's"
  },
  "status": "invalid_card_details"
}

{
  "brand": {
    "customer_service_phone_number": "8020202020",
    "id": 52,
    "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg",
    "name": "McDonald's"
  },
  "status": "insufficient_funds"
}

{
  "brand": {
    "customer_service_phone_number": "8020202020",
    "id": 52,
    "logo_image_src": "https://cdn.foodkitapp.io/brands/51/logo_image_src.100x100.jpg",
    "name": "McDonald's"
  },
  "status": "payment_failed"
}
```

**Comment by coreymcmahon** [comment]
@coreymcmahon will look at the Omise dashboard after the call to try and find out if there are other status codes occurring frequently that we should provide client-visible error messages for.

**Pull request merged**
